apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.label }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: {{ .Values.ingress.soliter.entery_path }}
        pathType: {{ .Values.ingress.soliter.pathType }}
        backend:
          service:
            name: {{ .Values.ingress.soliter.service }}
            port:
              number: {{ .Values.ingress.soliter.port }}

      - path: {{ .Values.ingress.weatherapp.entery_path }}
        pathType: {{ .Values.ingress.weatherapp.pathType }}
        backend:
          service:
            name: {{ .Values.service.name }}
            port:
              number: {{ .Values.ingress.weatherapp.port }}

