apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.PV.name }}
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: {{ .Values.PV.size }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.PV.pvc_mode }}
  storageClassName: ""
  persistentVolumeReclaimPolicy: Delete
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-0f61c681c8aacba91
